In [2]:
import pandas as pd
import os

In [3]:
dataset = pd.read_csv("/Users/saharlahershi/Desktop/Somali_Trees_Data/Somali_Trees_Cleaned/Tree_Climatic_Zones.csv")
dataset

              Botanical_Name    A    B    C    D    E
0          Salvadora persica  Yes  Yes  NaN  Yes  NaN
1            Acacia tortilis  Yes  Yes  Yes  Yes  Yes
2            Tamarix aphylla  Yes  Yes  NaN  Yes  NaN
3              Acacia bussei  Yes  Yes  Yes  Yes  Yes
4        Ziziphus mauritiana  Yes  Yes  NaN  Yes  NaN
5          Cordeauxia edulis  Yes  Yes  Yes  NaN  NaN
6         Prosopis juliflora  Yes  Yes  Yes  Yes  Yes
7             Acacia Senegal  Yes  Yes  NaN  Yes  NaN
8         Prosopis chilensis  NaN  Yes  NaN  Yes  NaN
9              Acacia albida  NaN  Yes  Yes  Yes  Yes
10           Acacia nilotica  NaN  Yes  NaN  Yes  NaN
11         Commiphora myrrha  NaN  Yes  Yes  Yes  Yes
12    Conocarpus lancifolius  NaN  Yes  Yes  Yes  NaN
13        Terminalia spinosa  NaN  Yes  Yes  Yes  NaN
14      Parkinsonia aculeata  NaN  Yes  Yes  Yes  Yes
15           Cordia sinensis  NaN  Yes  NaN  NaN  NaN
16   Casuarina equisetifolia  NaN  NaN  NaN  Yes  NaN
17  Eucalyptus camaldulensis  NaN  Yes  Yes  Yes  Yes
18      Balanites aegyptiaca  NaN  NaN  NaN  Yes  NaN
19        Boswellia frereana  NaN  NaN  Yes  NaN  Yes
20             Dobera glabra  NaN  Yes  NaN  Yes  NaN
21     Terminalia prunioides  NaN  Yes  NaN  Yes  NaN
22        Khaya senegalensis  NaN  NaN  NaN  Yes  Yes
23        Prosopis cineraria  NaN  NaN  NaN  Yes  NaN
24        Azadirachta indica  NaN  Yes  Yes  Yes  NaN
25         Juniperus excelsa  NaN  NaN  NaN  NaN  Yes
26           Albizia lebbeck  NaN  NaN  NaN  Yes  NaN
27             Cassia siamea  NaN  NaN  NaN  Yes  NaN
28             Schinus molle  NaN  NaN  NaN  NaN  Yes
29    Anacardium occidentale  NaN  NaN  NaN  Yes  NaN
30         Tamarindus indica  NaN  NaN  NaN  Yes  NaN
31     Leucaena leucocephala  NaN  NaN  NaN  Yes  NaN
32        Hyphaene compressa  Yes  Yes  NaN  Yes  NaN
33       Phoenix dactylifera  Yes  Yes  NaN  Yes  NaN
34          Mangifera indica  Yes  Yes  Yes  Yes  Yes
35       Citrus aurantifolia  Yes  Yes  Yes  Yes  Yes
36           Citrus paradisi  Yes  Yes  Yes  Yes  Yes
37      Sesbania grandiflora  Yes  Yes  NaN  Yes  NaN
38        Terminalia catappa  Yes  Yes  NaN  Yes  NaN
39           Annona muricata  Yes  Yes  Yes  Yes  NaN
40           Annona squamosa  NaN  NaN  Yes  NaN  Yes
41           Psidium guajava  Yes  Yes  Yes  Yes  Yes
42            Cocos nucifera  Yes  Yes  NaN  Yes  NaN

In [4]:
dataset_modified = dataset.copy()

In [5]:
dataset_melted = dataset_modified.melt(id_vars="Botanical_Name",value_vars=["A","B","C","D","E"],var_name="Climate_Zone",value_name="Status")
dataset_melted

          Botanical_Name Climate_Zone Status
0      Salvadora persica            A    Yes
1        Acacia tortilis            A    Yes
2        Tamarix aphylla            A    Yes
3          Acacia bussei            A    Yes
4    Ziziphus mauritiana            A    Yes
..                   ...          ...    ...
210   Terminalia catappa            E    NaN
211      Annona muricata            E    NaN
212      Annona squamosa            E    Yes
213      Psidium guajava            E    Yes
214       Cocos nucifera            E    NaN

[215 rows x 3 columns]

In [9]:
dataset_melted.isna().sum()

Botanical_Name     0
Climate_Zone       0
Status            96
dtype: int64

In [17]:
dataset_nulls_dropped = dataset_melted.dropna(subset= ["Status"])
dataset_nulls_dropped

          Botanical_Name Climate_Zone Status
0      Salvadora persica            A    Yes
1        Acacia tortilis            A    Yes
2        Tamarix aphylla            A    Yes
3          Acacia bussei            A    Yes
4    Ziziphus mauritiana            A    Yes
..                   ...          ...    ...
206     Mangifera indica            E    Yes
207  Citrus aurantifolia            E    Yes
208      Citrus paradisi            E    Yes
212      Annona squamosa            E    Yes
213      Psidium guajava            E    Yes

[119 rows x 3 columns]

rows left are equal to the orginal minus the 96 null valus in the Status column

In [19]:
dataset_final = dataset_nulls_dropped.drop(columns= "Status")
dataset_final

          Botanical_Name Climate_Zone
0      Salvadora persica            A
1        Acacia tortilis            A
2        Tamarix aphylla            A
3          Acacia bussei            A
4    Ziziphus mauritiana            A
..                   ...          ...
206     Mangifera indica            E
207  Citrus aurantifolia            E
208      Citrus paradisi            E
212      Annona squamosa            E
213      Psidium guajava            E

[119 rows x 2 columns]

In [20]:
dataset_final.to_csv("/Users/saharlahershi/Desktop/Somali_Trees_Data/Somali_Trees_Cleaned/Tree_Climatic_Zones_Final.csv", index=False)